name: Build and Publish Chocolatey Package

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install cmake and ninja
        run: |
          choco install cmake ninja -y
      
      - name: Configure CMake
        run: cmake -B build -G Ninja
      
      - name: Build and Test Package
        run: cmake --build build --target test_package
      
      # Upload the built package as an artifact
      - name: Upload Package Artifact
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v3
        with:
          name: choco-package
          path: build/inform7.*.nupkg
          retention-days: 1
  
  publish:
    needs: build
    if: github.event_name != 'pull_request'
    runs-on: windows-latest
    environment: production  # Specify the production environment
    steps:
      - uses: actions/checkout@v3
      
      # Download the package artifact from the build job
      - name: Download Package Artifact
        uses: actions/download-artifact@v3
        with:
          name: choco-package
          path: build
      
      - name: Install cmake and ninja
        run: |
          choco install cmake ninja -y
      
      - name: Configure CMake
        run: cmake -B build -G Ninja
      
      - name: Publish Package
        run: cmake --build build --target push
        env:
          CHOCOLATEY_API_KEY: ${{ secrets.CHOCOLATEY_API_KEY }} 