name: Build and Publish Chocolatey Package

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Chocolatey
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
          iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
      
      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: '3.20.x'
      
      - name: Configure CMake
        run: cmake -B build
      
      - name: Build and Test Package
        run: |
          cd build
          cmake --build . --target choco_uninstall
      
      # Only run on main branch or tag push, not PRs
      - name: Publish Package
        if: github.event_name != 'pull_request'
        run: |
          cd build
          cmake --build . --target push
        env:
          CHOCOLATEY_API_KEY: ${{ secrets.CHOCOLATEY_API_KEY }} 